version: 1.0.{build}
build_cloud: Docker
image: Linux
clone_depth: 3
environment:
  docker_image: golang:latest
  docker_pull: always
build: off
test_script:
- sh: >-
    printenv
    
    go version
    
    go get ./...
    
    go vet ./...
    
    go test -v ./...
deploy: off
notifications:
- provider: Email
  to:
  - batmac@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
