sudo: false
language: go

go:
  - "1.x"
  - "1.11.x"
  - "1.10.x"
  - "1.7"
  - master

os:
  - linux
  - osx
  - windows

script:
  - go test -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

matrix:
  fast_finish: true
  allow_failures:
    - go: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
